### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by sholtomaud** [awslabs/cloudfront-hosting-toolkit#3]
### Expected Behaviour

it works

### Current Behaviour

your doco is wrong, and it doesn't work. fix it you Billion $ company! 
![image](https://github.com/awslabs/cloudfront-hosting-toolkit/assets/398402/7e927d4a-8df0-4a5a-aeaa-b1114e4029ec)

![image](https://github.com/awslabs/cloudfront-hosting-toolkit/assets/398402/4af119b5-1f94-4e4f-82af-1694bb470ffb)

### Code snippet

```python
yeah nah
```

### Steps to Reproduce

fix is

**Comment by cornelcroi** [comment]
Thank you for opening this issue and bringing it to our attention. We have addressed the problem and it has now been fixed. If you encounter any further issues or have any additional questions, please don't hesitate to let us know.

**Comment by sholtomaud** [comment]
Nope not fixed. look at your doco. look at npm. 

go through your cdk steps in detal. sjc
